name: Sync Repo

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  retrieve-info:
    name: Retrieve Repo Info
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      REPO_FULL_NAME: ${{ github.repository }}
    outputs:
      upstream_full_name: ${{ steps.upstream-info.outputs.UPSTREAM_FULL_NAME }}
      upstream_default_branch: ${{ steps.upstream-info.outputs.UPSTREAM_DEFAULT_BRANCH }}
      upstream_branches: ${{ steps.get-branches.outputs.UPSTREAM_BRANCHES }}
    steps:
      - name: Retrieve Upstream Repo Info
        id: upstream-info
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          response=$(curl -s -H "Authorization: token $GH_TOKEN" "https://api.github.com/repos/$REPO_FULL_NAME")
          echo "Fetching repository information via Github API..."

          if [ -z "$response" ]; then
            echo "Failed to retrieve repository information."
            exit 1
          fi

          if ! echo "$response" | jq -e '.parent' >/dev/null; then
            echo "This repository is not a fork."
            exit 1
          fi

          name=$(echo "$response" | jq -r '.parent.name')
          echo "UPSTREAM_REPO=$name" >> "$GITHUB_ENV"

          html_url=$(echo "$response" | jq -r '.parent.html_url')
          echo "UPSTREAM_REPO_URL=$html_url" >> "$GITHUB_ENV"

          full_name=$(echo "$response" | jq -r '.parent.full_name')
          echo "UPSTREAM_FULL_NAME=$full_name" >> "$GITHUB_OUTPUT"

          default_branch=$(echo "$response" | jq -r '.parent.default_branch')
          echo "UPSTREAM_DEFAULT_BRANCH=$default_branch" >> "$GITHUB_OUTPUT"

      - name: Retrieve Upstream Branches
        id: get-branches
        run: |
          branches=$(git ls-remote --heads "$UPSTREAM_REPO_URL" | awk '{print $2}' | sed -E 's|refs/heads/||g' | tr -d '[:cntrl:]')
          echo "Fetching branches from $UPSTREAM_REPO..."

          if [[ -z "$branches" ]]; then
            echo "No branches found! Exiting..."
            exit 1
          fi

          if ! branches_json=$(echo "$branches" | jq -Rcs 'split("\n") | map(select(length > 0))'); then
            echo "Error: Failed to generate valid JSON!"
            exit 1
          fi

          echo "Upstream branches JSON array: $branches_json"
          echo "UPSTREAM_BRANCHES=$branches_json" >> "$GITHUB_OUTPUT"

  sync-fork:
    name: Sync Forked Repo
    runs-on: ubuntu-latest
    needs: retrieve-info
    permissions:
      contents: write
    strategy:
      matrix:
        branches: ${{ fromJson(needs.retrieve-info.outputs.UPSTREAM_BRANCHES) }}
    outputs:
      repo_tags: ${{ steps.sync-tags.outputs.REPO_TAGS }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync Tags to Fork Repo
        id: sync-tags
        env:
          UPSTREAM_URL: https://github.com/${{ needs.retrieve-info.outputs.upstream_full_name }}.git
          SYNC_BRANCH: ${{ matrix.branches }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          if ! git remote get-url upstream &> /dev/null; then
            git remote add upstream "$UPSTREAM_URL"
          fi

          git sparse-checkout set --no-cone --stdin <<EOF
          /*
          !.github/workflows/
          EOF

          git fetch --tags upstream || { echo "Failed to fetch tags"; exit 1; }
          echo "Fetched tags: $(git tag -l)"

          if git show-ref --verify --quiet "refs/heads/$SYNC_BRANCH"; then
            git checkout "$SYNC_BRANCH"
          else
            git checkout -b "$SYNC_BRANCH" "upstream/$SYNC_BRANCH"
          fi

          git pull --rebase upstream "$SYNC_BRANCH"
          git push origin "$SYNC_BRANCH"

          tag_count=$(git tag -l | wc -l)
          if [ "$tag_count" -gt 0 ]; then
            git push origin --tags
            tags_json=$(git tag --sort=creatordate | jq -R . | jq -cs .)
            echo "REPO_TAGS=$tags_json" >> "$GITHUB_OUTPUT"
          else
            echo "No tags to sync."
            echo "REPO_TAGS=[]" >> "$GITHUB_OUTPUT"
          fi

  build-and-push-images:
    name: Build & Push Images to Registries
    needs:
      - retrieve-info
      - sync-fork
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        registry: [ghcr, dockerhub]
    uses: ./.github/workflows/build-and-push-docker-images-chunked.yml
    with:
      repo_tags: ${{ fromJson(needs.sync-fork.outputs.repo_tags) }}
      registry: ${{ matrix.registry }}
      upstream_full_name: ${{ needs.retrieve-info.outputs.upstream_full_name }}
